# platform :ios, '9.0'

target 'BusRoutes' do
  use_frameworks!

  pod 'Kingfisher', '~> 4.8'
  pod 'SwiftLint'

  target 'BusRoutesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
